function SetFigProp(figSize, fontSize)
%SETFIGPROP Set figure proportions
%   Written by: Z.J. Chen
%   Last modified by: J.X.J. Bannwarth, 10/05/2017
    set( gca, 'FontSize',               fontSize, ...
              'LineWidth',              0.5,      ...
              'TitleFontWeight',        'normal', ...
              'TitleFontSizeMultiplier', 1,       ...
              'LabelFontSizeMultiplier', 1        )

    set( gcf, 'PaperUnits',        'centimeters',   ...
              'PaperPositionMode', 'manual',        ...
              'PaperPosition',     [0, 0, figSize], ...
              'PaperSize',         figSize,         ...
              'Color',             [1, 1, 1]        )

    set( get(gca, 'xlabel'), 'FontSize', fontSize )
    set( get(gca, 'ylabel'), 'FontSize', fontSize )
    set( get(gca, 'title'),  'FontSize', fontSize )
    
    set( gca, 'TickLabelInterpreter', 'latex' )
end