function cellInfo = BusAttitude(varargin)
%BUSATTITUDE Returns a cell array containing bus object information.
%
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the MATLAB file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

%% battery_statusBus
cellInfo = { ...
  { ...
    'battery_statusBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
        {'scale', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

Simulink.Bus.cellToObject(cellInfo)

%% manual_control_spBus
cellInfo = { ...
  { ...
    'manual_control_spBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
        {'r', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'x', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'y', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'z', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

Simulink.Bus.cellToObject(cellInfo)

%% ctrl_stateBus
cellInfo = { ...
  { ...
    'ctrl_stateBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
        {'pitch_rate', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'q', 4, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'roll_rate', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'timestamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'yaw_rate', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

Simulink.Bus.cellToObject(cellInfo)

%% vehicle_statusBus
cellInfo = { ...
  { ...
    'vehicle_statusBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
        {'is_rotary_wing', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

Simulink.Bus.cellToObject(cellInfo)

%% v_att_spBus
cellInfo = { ...
  { ...
    'v_att_spBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
        {'disable_mc_yaw_control', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'landing_gear', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'q_d', 4, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'thrust', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'yaw_sp_move_rate', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

Simulink.Bus.cellToObject(cellInfo)

%% v_rates_spBus
cellInfo = { ...
  { ...
    'v_rates_spBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
        {'pitch', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'roll', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'thrust', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'thurst', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'timestamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'yaw', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

Simulink.Bus.cellToObject(cellInfo)

%% flagsBus
cellInfo = { ...
  { ...
    'flagsBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
        {'pitch_neg', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'pitch_pos', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'roll_neg', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'roll_pos', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'yaw_neg', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'yaw_pos', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

Simulink.Bus.cellToObject(cellInfo)

% saturation_statusBus
cellInfo = { ...
  { ...
    'saturation_statusBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
        {'flags', 1, 'Bus: flagsBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

Simulink.Bus.cellToObject(cellInfo)

%% armedBus
cellInfo = { ...
  { ...
    'armedBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
        {'armed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

Simulink.Bus.cellToObject(cellInfo)


%% actuatorsBus
cellInfo = { ...
  { ...
    'actuatorsBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
        {'control', 8, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'timestamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'timestamp_sample', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

Simulink.Bus.cellToObject(cellInfo)

%% paramsBus
cellInfo = { ...
  { ...
    'paramsBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
        {'acro_rate_max', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'actuators_0_circuit_breaker_enabled', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'att_p', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'auto_rate_max', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'bat_scale_en', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'mc_rate_max', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'rate_d', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'rate_ff', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'rate_i', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'rate_int_lim', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'rate_p', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'rattitude_thres', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'tpa_breakpoint_d', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'tpa_breakpoint_i', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'tpa_breakpoint_p', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'tpa_rate_d', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'tpa_rate_i', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'tpa_rate_p', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'vtol_wv_yaw_rate_scale', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'vtol_opt_recovery_enabled', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'vtol_type', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'yaw_ff', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

Simulink.Bus.cellToObject(cellInfo)

% v_control_modeBus
cellInfo = { ...
  { ...
    'v_control_modeBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
        {'flag_control_attitude_enabled', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'flag_control_auto_enabled', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'flag_control_manual_enabled', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'flag_control_rates_enabled', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'flag_control_velocity_enabled', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

Simulink.Bus.cellToObject(cellInfo)

%% controller_statusBus
cellInfo = { ...
  { ...
    'controller_statusBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
        {'pitch_rate_integ', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'roll_rate_integ', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'timestamp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'yaw_rate_integ', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

Simulink.Bus.cellToObject(cellInfo)

cellInfo = { ...
  { ...
    'selfBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
        {'att_control', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'init', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'last_run', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'rates_int', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'rates_prev', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'rates_sp', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'rates_sp_prev', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'thrust_sp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'yaw_ff', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        % Buses
        {'battery_status', 1, 'Bus: battery_statusBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'manual_control_sp', 1, 'Bus: manual_control_spBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'ctrl_state', 1, 'Bus: ctrl_stateBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'vehicle_status', 1, 'Bus: vehicle_statusBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'v_att_sp', 1, 'Bus: v_att_spBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'v_rates_sp', 1, 'Bus: v_rates_spBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'saturation_status', 1, 'Bus: saturation_statusBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'flags', 1, 'Bus: flagsBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'armed', 1, 'Bus: armedBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'actuators', 1, 'Bus: actuatorsBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'params', 1, 'Bus: paramsBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'v_control_mode', 1, 'Bus: v_control_modeBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
        {'controller_status', 1, 'Bus: controller_statusBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end