% 2015b code
throttle_hover = THROTTLE_HOVER; % evalin('base', THROTTLE_HOVER);
MPC_INIT_SELF = struct( 'mpc_param_find', struct( ...
'MC_YAWRATE_MAX', str2num(MC_YAWRATE_MAX), ...
'MC_YAW_P', str2num(MC_YAW_P), ...
'MPC_ACC_HOR_MAX', str2num(MPC_ACC_HOR_MAX), ...
'MPC_ALTCTL_DY', str2num(MPC_ALTCTL_DY), ...
'MPC_ALTCTL_DZ', str2num(MPC_ALTCTL_DZ), ...
'MPC_ALT_MODE', str2num(MPC_ALT_MODE), ...
'MPC_HOLD_MAX_XY', str2num(MPC_HOLD_MAX_XY), ...
'MPC_HOLD_MAX_Z', str2num(MPC_HOLD_MAX_Z), ...
'MPC_HOLD_XY_DZ', str2num(MPC_HOLD_XY_DZ), ...
'MPC_LAND_SPEED', str2num(MPC_LAND_SPEED), ...
'MPC_MAN_P_MAX', str2num(MPC_MAN_P_MAX), ...
'MPC_MAN_R_MAX', str2num(MPC_MAN_R_MAX), ...
'MPC_MAN_Y_MAX', str2num(MPC_MAN_Y_MAX), ...
'MPC_THR_HOVER', str2num(MPC_THR_HOVER), ...
'MPC_THR_MAX', str2num(MPC_THR_MAX), ...
'MPC_THR_MIN', str2num(MPC_THR_MIN), ...
'MPC_TILTMAX_AIR', str2num(MPC_TILTMAX_AIR), ...
'MPC_TILTMAX_LND', str2num(MPC_TILTMAX_LND), ...
'MPC_TKO_SPEED', str2num(MPC_TKO_SPEED), ...
'MPC_XY_CRUISE', str2num(MPC_XY_CRUISE), ...
'MPC_XY_FF', str2num(MPC_XY_FF), ...
'MPC_XY_P', str2num(MPC_XY_P), ...
'MPC_XY_VEL_D', str2num(MPC_XY_VEL_D), ...
'MPC_XY_VEL_I', str2num(MPC_XY_VEL_I), ...
'MPC_XY_VEL_MAX', str2num(MPC_XY_VEL_MAX), ...
'MPC_XY_VEL_P', str2num(MPC_XY_VEL_P), ...
'MPC_Z_FF', str2num(MPC_Z_FF), ...
'MPC_Z_P', str2num(MPC_Z_P), ...
'MPC_Z_VEL_D', str2num(MPC_Z_VEL_D), ...
'MPC_Z_VEL_I', str2num(MPC_Z_VEL_I), ...
'MPC_Z_VEL_MAX', str2num(MPC_Z_VEL_MAX), ...
'MPC_Z_VEL_MAX_DN', str2num(MPC_Z_VEL_MAX_DN), ...
'MPC_Z_VEL_MAX_UP', str2num(MPC_Z_VEL_MAX_UP), ...
'MPC_Z_VEL_P', str2num(MPC_Z_VEL_P), ...
'VT_OPT_RECOV_EN', str2num(VT_OPT_RECOV_EN), ...
'MPC_VELD_LP', str2num(MPC_VELD_LP) ...
), ...
'mpc_thrust_int', [0; 0; -throttle_hover], ...
'mpc_att_sp', struct('thrust', throttle_hover, ...
'q_d', [1; 0; 0; 0;]) ...
);